FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Exponemos el puerto por defecto de Vite
EXPOSE 5173

# CRÍTICO: Pasamos '--host' para que Vite exponga el servidor fuera del contenedor
CMD ["npm", "run", "dev", "--", "--host"]