// This file was generated by Prisma
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Agregamos el fallback con la URL de nuestro contenedor para que NUNCA sea undefined
    url: process.env.DATABASE_URL || "postgresql://dev_user:dev_password_2026@db:5432/facadmin_inventario?schema=public",
  },
});